//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckingAds
    {
        public int id_CheckingAds { get; set; }
        public string NameChecking { get; set; }
        public string Remarks { get; set; }
        public int id_Director { get; set; }
        public int id_advertising { get; set; }
    
        public virtual Advertising Advertising { get; set; }
        public virtual Director Director { get; set; }
    }
}
