//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVcompanyEntities : DbContext
    {
        public TVcompanyEntities()
            : base("name=TVcompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Advertising> Advertising { get; set; }
        public virtual DbSet<AgeRestrictions> AgeRestrictions { get; set; }
        public virtual DbSet<Analyst> Analyst { get; set; }
        public virtual DbSet<CheckingAds> CheckingAds { get; set; }
        public virtual DbSet<CheckingAgeLimit> CheckingAgeLimit { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomersBalance> CustomersBalance { get; set; }
        public virtual DbSet<DesiredDisplayTime> DesiredDisplayTime { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Esters> Esters { get; set; }
        public virtual DbSet<InternalCurrency> InternalCurrency { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<PreparationProgram> PreparationProgram { get; set; }
        public virtual DbSet<ProgramRelease> ProgramRelease { get; set; }
        public virtual DbSet<PurchaseAds> PurchaseAds { get; set; }
        public virtual DbSet<PurchaseOfCurrency> PurchaseOfCurrency { get; set; }
        public virtual DbSet<ResultChecking> ResultChecking { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Telecast> Telecast { get; set; }
    }
}
