//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparationProgram
    {
        public int id_PreparationProgram { get; set; }
        public string NameProgram { get; set; }
        public Nullable<int> id_advertising { get; set; }
        public Nullable<int> id_Esters { get; set; }
        public Nullable<int> id_telecast { get; set; }
        public int id_Analyst { get; set; }
        public int id_ProgramRelease { get; set; }
    
        public virtual Advertising Advertising { get; set; }
        public virtual Analyst Analyst { get; set; }
        public virtual Esters Esters { get; set; }
        public virtual ProgramRelease ProgramRelease { get; set; }
        public virtual Telecast Telecast { get; set; }
    }
}
