//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOfCurrency
    {
        public int id_Purchase { get; set; }
        public string ConfirmationOfPurchase { get; set; }
        public int id_CustomersBalance { get; set; }
        public int id_InternalCurrency { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual CustomersBalance CustomersBalance { get; set; }
        public virtual InternalCurrency InternalCurrency { get; set; }
    }
}
